# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Klines_1Cpp <- function(x, y, regressionMethod) {
    .Call(`_gR2_Klines_1Cpp`, x, y, regressionMethod)
}

Klines_not_1Cpp <- function(x, y, K, num_init, regressionMethod, genotypeVector, minRelativeGroupSize) {
    .Call(`_gR2_Klines_not_1Cpp`, x, y, K, num_init, regressionMethod, genotypeVector, minRelativeGroupSize)
}

