# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Klines_eachCppOut <- function(x, y, K, regressionMethod) {
    .Call(`_gR2_Klines_eachCppOut`, x, y, K, regressionMethod)
}

Klines_1Cpp <- function(x, y, regressionMethod) {
    .Call(`_gR2_Klines_1Cpp`, x, y, regressionMethod)
}

